# Generated by Django 3.2.4 on 2021-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('rom', models.CharField(blank=True, max_length=10, null=True)),
                ('ram', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('product_link', models.TextField(blank=True, null=True)),
                ('primary_matched_links', models.TextField(blank=True, null=True)),
                ('secondary_matched_links', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
