# Generated by Django 3.2.4 on 2021-06-27 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price_comparision_api', '0002_alter_products_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='release_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
